### ISSUE TITLE
40MB of dependencies?

### ISSUE THREAD

**Issue by My1** [thecsea/twofactor-dir#1]
I just ran a composer install on the freshly downloaded release of this thing and I got 40.5MB (it even says 5MB on disk) in the vendor folder.

The files and the src folder together take just 13.1KB (24KB on disk)
why do you need an overhead of 3 THOUSAND times for this?

I have seen some other 2FA related thing here on github (instant2fa to be exact) and reduced it from about 12MB of dependencies on a 10kb source and I slimmed it down to 5.49 with no composer dependencies whatsoever. and because this seems so weird I wanna ask why this thing needs so much in dependencies...

**Comment by carduz** [comment]
Maybe you have installed also the dev dependencies

**Comment by My1** [comment]
there are dev dependencies?
I personally never really liked composer back in the alpha stage, because well it's alpha software but ever since it's stable I kinda use it for the stuff that needs it.
but if there are dependencies that arent needed it REALLY should drop down to the stuff that's actually needed instead of bloating your files with WAY too many files. at least per default.
if it's not in by default, how can I change this?
when I just run `composer install` (as written in pretty much any github project that uses composer) I dont expect it to download tons of bloat that isnt needed to use it.
and honestly that's one more reason why I prefer neatly packaged, ready to run (or integrate) releases, because any dev tools that may or may not be needed arent included so you dont need to get thousands of files. I mean it's not just about the size. I didnt count the files but instant2fa with its almost 12MB has 3 thousand files and many small files move very slowly due to filesystem overhead.

also dev tools are usually needed to for example mod the code, but for plain running and stuff not really...

**Comment by carduz** [comment]
To do that you have to type `composer install --no-dev`. This is the way used by any modern package managers, like npm.

**Comment by My1** [comment]
this is completely stupid, why are package managers installing so much by default I mean the bloat is HUGE, especially in a case like this. most software installers I know are usually putting any dev or debug thing in the advanced options or whatever but not as default.
is there a way to disable dev requirements permanently?

**Comment by carduz** [comment]
I think you should ask this question to package mangers creators.

In my opinion it is very useful have dev dependencies installed by default. So I don't know how to disable them permanently.
Of course deploying system like heroku default env for php disable dev dependencies.
